
MOVE_AHEAD = 'MoveAhead'
ROTATE_LEFT = 'RotateLeft'
ROTATE_RIGHT = 'RotateRight'
LOOK_UP = 'LookUp'
LOOK_DOWN = 'LookDown'

LOOK_TOMATO = 'LookTomato'
LOOK_BOWL = 'LookBowl'
LOOK_OBJECT = 'LookObject'
DONE = 'Done'

BASIC_ACTIONS = [MOVE_AHEAD, ROTATE_LEFT, ROTATE_RIGHT, LOOK_UP, LOOK_DOWN, LOOK_TOMATO, LOOK_BOWL, DONE]

GOAL_SUCCESS_REWARD = 5
STEP_PENALTY = -0.05
FAILED_ACTION_PENALTY = 0